# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the canon branch
  push:
    branches: [ canon ]
  pull_request:
    branches: [ canon ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Cache
        uses: actions/cache@v2.1.6
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: C:\gtk-build
          key: the-cache-smdh
      - uses: actions/checkout@v2
        with:
          # Repository name with owner. For example, actions/checkout
          # Default: ${{ github.repository }}
          repository: 'wingtk/gvsbuild'
      # Runs a set of commands using the runners shell
      - name: Run the build
        run: |
          python build.py build --fast-build -p x64 --vs-ver 16 gtk3
          ls C:\gtk-build\gtk\x64\release
#       - uses: actions/upload-artifact@v2
#         with:
#           name: 
#           path: 
